import Nav from "@/components/Nav/Nav";
import Image from "next/image";

import logo from '../../../public/logo-black.svg';

export const metadata = {
  title: "Create Next App",
  description: 'Generated by create next app'
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="portfolio__nav-wrapper">
                <Image className='logo' src={logo} width={150} height={150} alt="logo"/>
                <Nav color={'black'}/>
        </header>
        {children}
      </body>
    </html>
  )
}