import './globals.css';
import Hamburger from '@/components/hamburger/hamburger';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Hamburger color="white" />
        {children}
      </body>
    </html>
  );
}
